apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
  labels:
    app: chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: ${DOCKER_IMAGE}  # Set via envsubst in your workflow
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            name: web
        env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "80"
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai-api-key
                key: OPENAI_API_KEY
