apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbot-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"  # For GKE Autopilot using the GCE Ingress controller.
spec:
  rules:
  - http:
      paths:
      - path: /api/chat
        pathType: Prefix
        backend:
          service:
            name: chatbot-server-service
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chatbot-client-service
            port:
              number: 80
