apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  selector:
    app: chatbot
  ports:
    - name: client
      port: 3000
      targetPort: 3000
    - name: server
      port: 5000
      targetPort: 5000
