apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  selector:
    app: chatbot
  ports:
    - name: client
      port: 80
      targetPort: client  # Matches the container port named "client" (3000)
    - name: server
      port: 5000
      targetPort: server  # Matches the container port named "server" (5000)
